import {
  LogisticsAdapter,
  type PickupParams,
  type PickupResult,
  type TrackingEvent,
  type TrackingResult,
  type ServiceabilityResult,
  type CredentialField,
} from "./base";

// Shipway API — https://apidocs.shipway.com/
// Base URL: https://shipway.in/api/
// Auth: username (login ID) + password (license key) in every request body.
// Key endpoints:
//   POST /pushOrderData   — push order/shipment data into Shipway
//   POST /getOrderShipmentDetails — get tracking status for an order
//   GET  /carriers         — list available carrier IDs

const API_BASE = "https://shipway.in/api";

async function shipwayFetch(
  path: string,
  body: unknown,
): Promise<any> {
  const url = `${API_BASE}${path}`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(body),
  });

  const text = await response.text();
  try {
    return JSON.parse(text);
  } catch {
    return { raw: text, status: response.status };
  }
}

export class ShipwayAdapter extends LogisticsAdapter {
  readonly key = "shipway";
  readonly displayName = "Shipway";
  readonly region = "IN";
  readonly logoUrl = "/images/logistics/shipway.png";

  readonly credentialFields: CredentialField[] = [
    {
      key: "username",
      label: "Username",
      type: "text",
      required: true,
      placeholder: "Enter your Shipway username",
      helpText:
        "Your Shipway login ID. Found in the registration email from Shipway.",
    },
    {
      key: "licenseKey",
      label: "License Key",
      type: "password",
      required: true,
      placeholder: "Enter your Shipway license key",
      helpText:
        "Your Shipway license key / password. Found in the registration email from Shipway.",
    },
    {
      key: "carrierId",
      label: "Default Carrier ID",
      type: "text",
      required: false,
      placeholder: "e.g. 1 (Delhivery), 2 (BlueDart)",
      helpText:
        "The numeric carrier ID to use for shipments. Use GET /carriers to list all IDs.",
    },
    {
      key: "companyName",
      label: "Company Name",
      type: "text",
      required: true,
      placeholder: "Your company name",
      helpText: "The company name used when pushing orders to Shipway.",
    },
  ];

  /**
   * Push an order into Shipway for tracking and management.
   * Endpoint: POST /pushOrderData
   * Docs: https://apidocs.shipway.com/
   *
   * Required fields: username, password, carrier_id, awb, order_id,
   *   first_name, last_name, email, phone, products, company.
   *
   * Note: Shipway is primarily a tracking/aggregation platform. The AWB must be
   * pre-generated by the underlying carrier. If no AWB is provided, Shipway
   * cannot create a pickup with the carrier directly.
   */
  async createPickup(
    params: PickupParams,
    credentials: Record<string, string>,
  ): Promise<PickupResult> {
    const { username, licenseKey, carrierId, companyName } = credentials;

    // Shipway requires an AWB to be pre-assigned. If one isn't provided,
    // we generate a placeholder reference. In production, the AWB should
    // come from the underlying carrier's API.
    const awb = params.awb || `RET-${params.returnId}`;
    const productsDesc =
      params.items
        .map((i) => `${i.name} x${i.quantity}`)
        .join(", ")
        .slice(0, 200) || "Return Shipment";

    const nameParts = params.senderName.split(" ");
    const firstName = nameParts[0] || "Customer";
    const lastName = nameParts.slice(1).join(" ") || "N/A";

    const payload = {
      username,
      password: licenseKey,
      carrier_id: carrierId || "1",
      awb,
      order_id: params.orderNumber,
      first_name: firstName,
      last_name: lastName,
      email: "noreply@example.com",
      phone: params.senderPhone.replace(/[^0-9]/g, "").slice(-10),
      products: productsDesc,
      company: companyName || "Store",
      pickup_address: params.senderAddress,
      pickup_city: params.senderCity,
      pickup_state: params.senderState,
      pickup_country: params.senderCountry || "India",
      pickup_pincode: params.senderPincode,
      shipping_address: params.receiverAddress,
      shipping_city: params.receiverCity,
      shipping_state: params.receiverState,
      shipping_country: params.receiverCountry || "India",
      shipping_pincode: params.receiverPincode,
      weight: (params.weight / 1000).toFixed(2),
      payment_mode: params.paymentMode === "cod" ? "COD" : "Prepaid",
    };

    try {
      const data = await shipwayFetch("/pushOrderData", payload);

      if (
        data?.status === "Success" ||
        data?.status === 200 ||
        data?.message?.toLowerCase().includes("success")
      ) {
        return {
          success: true,
          awb,
          trackingUrl: `https://shipway.in/track/${awb}`,
          rawResponse: data,
        };
      }

      return {
        success: false,
        error:
          data?.message || data?.error || "Failed to push order to Shipway",
        rawResponse: data,
      };
    } catch (err: any) {
      return {
        success: false,
        error: err.message || "Failed to create Shipway pickup",
      };
    }
  }

  /**
   * Get shipment tracking details from Shipway.
   * Endpoint: POST /getOrderShipmentDetails
   * Docs: https://apidocs.shipway.com/
   *
   * Required: username, password, order_id.
   * Note: You must first push data via pushOrderData before tracking.
   */
  async trackShipment(
    awb: string,
    credentials: Record<string, string>,
  ): Promise<TrackingResult> {
    const { username, licenseKey } = credentials;

    const payload = {
      username,
      password: licenseKey,
      order_id: awb, // Shipway tracks by order_id; AWB is used as reference
    };

    try {
      const data = await shipwayFetch("/getOrderShipmentDetails", payload);

      if (data?.status === "error" || data?.status === "Error") {
        return {
          success: false,
          awb,
          currentStatus: "Unknown",
          currentStatusCode: "",
          events: [],
          isDelivered: false,
          error: data?.message || "Tracking request failed",
          rawResponse: data,
        };
      }

      const shipment = data?.response || data;
      const scanDetails: any[] =
        shipment?.scan || shipment?.scans || shipment?.tracking_details || [];

      const events: TrackingEvent[] = scanDetails.map((scan: any) => ({
        timestamp: scan.time || scan.date_time || scan.timestamp || "",
        status: scan.status || scan.activity || "",
        statusCode: scan.status_code || "",
        location: scan.location || scan.city || "",
        description:
          scan.status_description || scan.activity || scan.status || "",
      }));

      const currentStatus =
        shipment?.current_status ||
        shipment?.status ||
        (events.length > 0 ? events[0].status : "In Transit");
      const currentStatusCode =
        shipment?.current_status_code || shipment?.status_code || "";
      const isDelivered =
        currentStatus.toLowerCase().includes("delivered") ||
        currentStatusCode === "DL";

      return {
        success: true,
        awb,
        currentStatus,
        currentStatusCode,
        events,
        isDelivered,
        rawResponse: data,
      };
    } catch (err: any) {
      return {
        success: false,
        awb,
        currentStatus: "Error",
        currentStatusCode: "",
        events: [],
        isDelivered: false,
        error: err.message || "Failed to track shipment",
      };
    }
  }

  /**
   * Shipway is primarily a tracking aggregator and does not provide
   * direct pincode serviceability checks. This method returns a default
   * serviceable response since serviceability depends on the underlying carrier.
   *
   * TODO: If Shipway adds a serviceability endpoint, implement it here.
   * Docs: https://apidocs.shipway.com/
   */
  async checkServiceability(
    _originPin: string,
    _destPin: string,
    _credentials: Record<string, string>,
  ): Promise<ServiceabilityResult> {
    // Shipway does not have a built-in serviceability check endpoint.
    // Serviceability depends on the underlying carrier.
    return {
      serviceable: true,
      error:
        "Shipway does not provide serviceability checks. Check with the underlying carrier.",
    };
  }

  /**
   * Validate Shipway credentials by attempting a lightweight API call.
   * We call getOrderShipmentDetails with a dummy order_id; a valid
   * credential set will return a structured error (order not found)
   * rather than an auth failure.
   */
  async validateCredentials(
    credentials: Record<string, string>,
  ): Promise<{ valid: boolean; error?: string }> {
    const { username, licenseKey } = credentials;

    if (!username || !licenseKey) {
      return {
        valid: false,
        error: "Both username and license key are required",
      };
    }

    try {
      const data = await shipwayFetch("/getOrderShipmentDetails", {
        username,
        password: licenseKey,
        order_id: "VALIDATE_CREDS_TEST_000",
      });

      // Auth failures typically return specific error messages
      if (
        data?.raw &&
        typeof data.raw === "string" &&
        (data.raw.toLowerCase().includes("unauthorized") ||
          data.raw.toLowerCase().includes("invalid") ||
          data.raw.toLowerCase().includes("authentication"))
      ) {
        return { valid: false, error: "Invalid username or license key" };
      }

      if (data?.status === 401 || data?.status === 403) {
        return { valid: false, error: "Invalid username or license key" };
      }

      // Any structured response (even "order not found") means creds are valid
      return { valid: true };
    } catch (err: any) {
      return {
        valid: false,
        error: err.message || "Failed to validate credentials",
      };
    }
  }

  /**
   * Shipway does not provide a direct cancel endpoint for pickups since it is
   * a tracking aggregator. Cancellation must happen on the underlying carrier.
   *
   * TODO: If Shipway adds a cancellation endpoint, implement it here.
   * Docs: https://apidocs.shipway.com/
   */
  async cancelPickup(
    _awb: string,
    _credentials: Record<string, string>,
  ): Promise<{ success: boolean; error?: string }> {
    return {
      success: false,
      error:
        "Shipway does not support direct pickup cancellation. Cancel via the underlying carrier.",
    };
  }
}
